<?php
/**
 * ConnectionsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiIdaasSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * IDaaS API
 *
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Mydex\ApiIdaasSdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Mydex\ApiIdaasSdk\ApiException;
use Mydex\ApiIdaasSdk\Configuration;
use Mydex\ApiIdaasSdk\FormDataProcessor;
use Mydex\ApiIdaasSdk\HeaderSelector;
use Mydex\ApiIdaasSdk\ObjectSerializer;

/**
 * ConnectionsApi Class Doc Comment
 *
 * @category Class
 * @package  Mydex\ApiIdaasSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConnectionsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'postFtcSetup' => [
            'application/json',
        ],
        'postIdentify' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation postFtcSetup
     *
     * Set up a First Time Connection URL.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\FtcSetupRequestBody|null $ftc_setup_request_body ftc_setup_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postFtcSetup'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiIdaasSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiIdaasSdk\Model\FtcUrlResponse|\Mydex\ApiIdaasSdk\Model\ErrorResponse|\Mydex\ApiIdaasSdk\Model\AuthErrorResponse
     */
    public function postFtcSetup($ftc_setup_request_body = null, string $contentType = self::contentTypes['postFtcSetup'][0])
    {
        list($response) = $this->postFtcSetupWithHttpInfo($ftc_setup_request_body, $contentType);
        return $response;
    }

    /**
     * Operation postFtcSetupWithHttpInfo
     *
     * Set up a First Time Connection URL.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\FtcSetupRequestBody|null $ftc_setup_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postFtcSetup'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiIdaasSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiIdaasSdk\Model\FtcUrlResponse|\Mydex\ApiIdaasSdk\Model\ErrorResponse|\Mydex\ApiIdaasSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function postFtcSetupWithHttpInfo($ftc_setup_request_body = null, string $contentType = self::contentTypes['postFtcSetup'][0])
    {
        $request = $this->postFtcSetupRequest($ftc_setup_request_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\FtcUrlResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiIdaasSdk\Model\FtcUrlResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\FtcUrlResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation postFtcSetupAsync
     *
     * Set up a First Time Connection URL.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\FtcSetupRequestBody|null $ftc_setup_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postFtcSetup'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postFtcSetupAsync($ftc_setup_request_body = null, string $contentType = self::contentTypes['postFtcSetup'][0])
    {
        return $this->postFtcSetupAsyncWithHttpInfo($ftc_setup_request_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postFtcSetupAsyncWithHttpInfo
     *
     * Set up a First Time Connection URL.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\FtcSetupRequestBody|null $ftc_setup_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postFtcSetup'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postFtcSetupAsyncWithHttpInfo($ftc_setup_request_body = null, string $contentType = self::contentTypes['postFtcSetup'][0])
    {
        $returnType = '\Mydex\ApiIdaasSdk\Model\FtcUrlResponse';
        $request = $this->postFtcSetupRequest($ftc_setup_request_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postFtcSetup'
     *
     * @param  \Mydex\ApiIdaasSdk\Model\FtcSetupRequestBody|null $ftc_setup_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postFtcSetup'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postFtcSetupRequest($ftc_setup_request_body = null, string $contentType = self::contentTypes['postFtcSetup'][0])
    {



        $resourcePath = '/ftc/setup';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($ftc_setup_request_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($ftc_setup_request_body));
            } else {
                $httpBody = $ftc_setup_request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postIdentify
     *
     * Set up an identification URL.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\IdentifyRequestBody|null $identify_request_body identify_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postIdentify'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiIdaasSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiIdaasSdk\Model\IdentifyUrlResponse|\Mydex\ApiIdaasSdk\Model\ErrorResponse|\Mydex\ApiIdaasSdk\Model\AuthErrorResponse
     */
    public function postIdentify($identify_request_body = null, string $contentType = self::contentTypes['postIdentify'][0])
    {
        list($response) = $this->postIdentifyWithHttpInfo($identify_request_body, $contentType);
        return $response;
    }

    /**
     * Operation postIdentifyWithHttpInfo
     *
     * Set up an identification URL.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\IdentifyRequestBody|null $identify_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postIdentify'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiIdaasSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiIdaasSdk\Model\IdentifyUrlResponse|\Mydex\ApiIdaasSdk\Model\ErrorResponse|\Mydex\ApiIdaasSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function postIdentifyWithHttpInfo($identify_request_body = null, string $contentType = self::contentTypes['postIdentify'][0])
    {
        $request = $this->postIdentifyRequest($identify_request_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\IdentifyUrlResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiIdaasSdk\Model\IdentifyUrlResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\IdentifyUrlResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation postIdentifyAsync
     *
     * Set up an identification URL.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\IdentifyRequestBody|null $identify_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postIdentify'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postIdentifyAsync($identify_request_body = null, string $contentType = self::contentTypes['postIdentify'][0])
    {
        return $this->postIdentifyAsyncWithHttpInfo($identify_request_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postIdentifyAsyncWithHttpInfo
     *
     * Set up an identification URL.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\IdentifyRequestBody|null $identify_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postIdentify'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postIdentifyAsyncWithHttpInfo($identify_request_body = null, string $contentType = self::contentTypes['postIdentify'][0])
    {
        $returnType = '\Mydex\ApiIdaasSdk\Model\IdentifyUrlResponse';
        $request = $this->postIdentifyRequest($identify_request_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postIdentify'
     *
     * @param  \Mydex\ApiIdaasSdk\Model\IdentifyRequestBody|null $identify_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postIdentify'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postIdentifyRequest($identify_request_body = null, string $contentType = self::contentTypes['postIdentify'][0])
    {



        $resourcePath = '/identify';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($identify_request_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($identify_request_body));
            } else {
                $httpBody = $identify_request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
