<?php
/**
 * IdentifiersApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiIdaasSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * IDaaS API
 *
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Mydex\ApiIdaasSdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Mydex\ApiIdaasSdk\ApiException;
use Mydex\ApiIdaasSdk\Configuration;
use Mydex\ApiIdaasSdk\FormDataProcessor;
use Mydex\ApiIdaasSdk\HeaderSelector;
use Mydex\ApiIdaasSdk\ObjectSerializer;

/**
 * IdentifiersApi Class Doc Comment
 *
 * @category Class
 * @package  Mydex\ApiIdaasSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IdentifiersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getIdentifierInvite' => [
            'application/json',
        ],
        'patchNotifyStatus' => [
            'application/json',
        ],
        'postInviteStatus' => [
            'application/json',
        ],
        'postNotifyMemberViaIdentifier' => [
            'application/json',
        ],
        'postStoreAndSendIdentifierInvite' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getIdentifierInvite
     *
     * Fetch an invitation code and identifier auth data.
     *
     * @param  string $invite The invitation code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getIdentifierInvite'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiIdaasSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiIdaasSdk\Model\GetInviteResponse|\Mydex\ApiIdaasSdk\Model\AuthErrorResponse
     */
    public function getIdentifierInvite($invite, string $contentType = self::contentTypes['getIdentifierInvite'][0])
    {
        list($response) = $this->getIdentifierInviteWithHttpInfo($invite, $contentType);
        return $response;
    }

    /**
     * Operation getIdentifierInviteWithHttpInfo
     *
     * Fetch an invitation code and identifier auth data.
     *
     * @param  string $invite The invitation code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getIdentifierInvite'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiIdaasSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiIdaasSdk\Model\GetInviteResponse|\Mydex\ApiIdaasSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getIdentifierInviteWithHttpInfo($invite, string $contentType = self::contentTypes['getIdentifierInvite'][0])
    {
        $request = $this->getIdentifierInviteRequest($invite, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\GetInviteResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiIdaasSdk\Model\GetInviteResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\GetInviteResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getIdentifierInviteAsync
     *
     * Fetch an invitation code and identifier auth data.
     *
     * @param  string $invite The invitation code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getIdentifierInvite'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getIdentifierInviteAsync($invite, string $contentType = self::contentTypes['getIdentifierInvite'][0])
    {
        return $this->getIdentifierInviteAsyncWithHttpInfo($invite, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getIdentifierInviteAsyncWithHttpInfo
     *
     * Fetch an invitation code and identifier auth data.
     *
     * @param  string $invite The invitation code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getIdentifierInvite'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getIdentifierInviteAsyncWithHttpInfo($invite, string $contentType = self::contentTypes['getIdentifierInvite'][0])
    {
        $returnType = '\Mydex\ApiIdaasSdk\Model\GetInviteResponse';
        $request = $this->getIdentifierInviteRequest($invite, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getIdentifierInvite'
     *
     * @param  string $invite The invitation code (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getIdentifierInvite'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getIdentifierInviteRequest($invite, string $contentType = self::contentTypes['getIdentifierInvite'][0])
    {

        // verify the required parameter 'invite' is set
        if ($invite === null || (is_array($invite) && count($invite) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $invite when calling getIdentifierInvite'
            );
        }


        $resourcePath = '/members/invite/{invite}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($invite !== null) {
            $resourcePath = str_replace(
                '{invite}',
                ObjectSerializer::toPathValue($invite),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation patchNotifyStatus
     *
     * Update the status of a notification.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\UpdateNotificationStatusRequestBody|null $update_notification_status_request_body update_notification_status_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchNotifyStatus'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiIdaasSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiIdaasSdk\Model\CreateIdentifierResponse|\Mydex\ApiIdaasSdk\Model\ErrorResponse|\Mydex\ApiIdaasSdk\Model\AuthErrorResponse
     */
    public function patchNotifyStatus($update_notification_status_request_body = null, string $contentType = self::contentTypes['patchNotifyStatus'][0])
    {
        list($response) = $this->patchNotifyStatusWithHttpInfo($update_notification_status_request_body, $contentType);
        return $response;
    }

    /**
     * Operation patchNotifyStatusWithHttpInfo
     *
     * Update the status of a notification.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\UpdateNotificationStatusRequestBody|null $update_notification_status_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchNotifyStatus'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiIdaasSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiIdaasSdk\Model\CreateIdentifierResponse|\Mydex\ApiIdaasSdk\Model\ErrorResponse|\Mydex\ApiIdaasSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function patchNotifyStatusWithHttpInfo($update_notification_status_request_body = null, string $contentType = self::contentTypes['patchNotifyStatus'][0])
    {
        $request = $this->patchNotifyStatusRequest($update_notification_status_request_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\CreateIdentifierResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiIdaasSdk\Model\CreateIdentifierResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\CreateIdentifierResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation patchNotifyStatusAsync
     *
     * Update the status of a notification.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\UpdateNotificationStatusRequestBody|null $update_notification_status_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchNotifyStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchNotifyStatusAsync($update_notification_status_request_body = null, string $contentType = self::contentTypes['patchNotifyStatus'][0])
    {
        return $this->patchNotifyStatusAsyncWithHttpInfo($update_notification_status_request_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation patchNotifyStatusAsyncWithHttpInfo
     *
     * Update the status of a notification.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\UpdateNotificationStatusRequestBody|null $update_notification_status_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchNotifyStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchNotifyStatusAsyncWithHttpInfo($update_notification_status_request_body = null, string $contentType = self::contentTypes['patchNotifyStatus'][0])
    {
        $returnType = '\Mydex\ApiIdaasSdk\Model\CreateIdentifierResponse';
        $request = $this->patchNotifyStatusRequest($update_notification_status_request_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'patchNotifyStatus'
     *
     * @param  \Mydex\ApiIdaasSdk\Model\UpdateNotificationStatusRequestBody|null $update_notification_status_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchNotifyStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function patchNotifyStatusRequest($update_notification_status_request_body = null, string $contentType = self::contentTypes['patchNotifyStatus'][0])
    {



        $resourcePath = '/members/notify/status';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_notification_status_request_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_notification_status_request_body));
            } else {
                $httpBody = $update_notification_status_request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postInviteStatus
     *
     * Check the status of an invite.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\InviteStatusRequestBody|null $invite_status_request_body invite_status_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postInviteStatus'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiIdaasSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiIdaasSdk\Model\InviteStatusResponse|\Mydex\ApiIdaasSdk\Model\AuthErrorResponse
     */
    public function postInviteStatus($invite_status_request_body = null, string $contentType = self::contentTypes['postInviteStatus'][0])
    {
        list($response) = $this->postInviteStatusWithHttpInfo($invite_status_request_body, $contentType);
        return $response;
    }

    /**
     * Operation postInviteStatusWithHttpInfo
     *
     * Check the status of an invite.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\InviteStatusRequestBody|null $invite_status_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postInviteStatus'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiIdaasSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiIdaasSdk\Model\InviteStatusResponse|\Mydex\ApiIdaasSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function postInviteStatusWithHttpInfo($invite_status_request_body = null, string $contentType = self::contentTypes['postInviteStatus'][0])
    {
        $request = $this->postInviteStatusRequest($invite_status_request_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\InviteStatusResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiIdaasSdk\Model\InviteStatusResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\InviteStatusResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation postInviteStatusAsync
     *
     * Check the status of an invite.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\InviteStatusRequestBody|null $invite_status_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postInviteStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postInviteStatusAsync($invite_status_request_body = null, string $contentType = self::contentTypes['postInviteStatus'][0])
    {
        return $this->postInviteStatusAsyncWithHttpInfo($invite_status_request_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postInviteStatusAsyncWithHttpInfo
     *
     * Check the status of an invite.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\InviteStatusRequestBody|null $invite_status_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postInviteStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postInviteStatusAsyncWithHttpInfo($invite_status_request_body = null, string $contentType = self::contentTypes['postInviteStatus'][0])
    {
        $returnType = '\Mydex\ApiIdaasSdk\Model\InviteStatusResponse';
        $request = $this->postInviteStatusRequest($invite_status_request_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postInviteStatus'
     *
     * @param  \Mydex\ApiIdaasSdk\Model\InviteStatusRequestBody|null $invite_status_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postInviteStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postInviteStatusRequest($invite_status_request_body = null, string $contentType = self::contentTypes['postInviteStatus'][0])
    {



        $resourcePath = '/members/invite/status';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($invite_status_request_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($invite_status_request_body));
            } else {
                $httpBody = $invite_status_request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postNotifyMemberViaIdentifier
     *
     * Send a notification to a member via its identifier.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\NotifyMemberRequestBody|null $notify_member_request_body notify_member_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postNotifyMemberViaIdentifier'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiIdaasSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiIdaasSdk\Model\CreateIdentifierResponse|\Mydex\ApiIdaasSdk\Model\ErrorResponse|\Mydex\ApiIdaasSdk\Model\AuthErrorResponse
     */
    public function postNotifyMemberViaIdentifier($notify_member_request_body = null, string $contentType = self::contentTypes['postNotifyMemberViaIdentifier'][0])
    {
        list($response) = $this->postNotifyMemberViaIdentifierWithHttpInfo($notify_member_request_body, $contentType);
        return $response;
    }

    /**
     * Operation postNotifyMemberViaIdentifierWithHttpInfo
     *
     * Send a notification to a member via its identifier.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\NotifyMemberRequestBody|null $notify_member_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postNotifyMemberViaIdentifier'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiIdaasSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiIdaasSdk\Model\CreateIdentifierResponse|\Mydex\ApiIdaasSdk\Model\ErrorResponse|\Mydex\ApiIdaasSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function postNotifyMemberViaIdentifierWithHttpInfo($notify_member_request_body = null, string $contentType = self::contentTypes['postNotifyMemberViaIdentifier'][0])
    {
        $request = $this->postNotifyMemberViaIdentifierRequest($notify_member_request_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\CreateIdentifierResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiIdaasSdk\Model\CreateIdentifierResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\CreateIdentifierResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation postNotifyMemberViaIdentifierAsync
     *
     * Send a notification to a member via its identifier.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\NotifyMemberRequestBody|null $notify_member_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postNotifyMemberViaIdentifier'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postNotifyMemberViaIdentifierAsync($notify_member_request_body = null, string $contentType = self::contentTypes['postNotifyMemberViaIdentifier'][0])
    {
        return $this->postNotifyMemberViaIdentifierAsyncWithHttpInfo($notify_member_request_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postNotifyMemberViaIdentifierAsyncWithHttpInfo
     *
     * Send a notification to a member via its identifier.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\NotifyMemberRequestBody|null $notify_member_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postNotifyMemberViaIdentifier'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postNotifyMemberViaIdentifierAsyncWithHttpInfo($notify_member_request_body = null, string $contentType = self::contentTypes['postNotifyMemberViaIdentifier'][0])
    {
        $returnType = '\Mydex\ApiIdaasSdk\Model\CreateIdentifierResponse';
        $request = $this->postNotifyMemberViaIdentifierRequest($notify_member_request_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postNotifyMemberViaIdentifier'
     *
     * @param  \Mydex\ApiIdaasSdk\Model\NotifyMemberRequestBody|null $notify_member_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postNotifyMemberViaIdentifier'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postNotifyMemberViaIdentifierRequest($notify_member_request_body = null, string $contentType = self::contentTypes['postNotifyMemberViaIdentifier'][0])
    {



        $resourcePath = '/members/notify';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($notify_member_request_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($notify_member_request_body));
            } else {
                $httpBody = $notify_member_request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postStoreAndSendIdentifierInvite
     *
     * Store an invitation code and send notification.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\InviteRequestBody|null $invite_request_body invite_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postStoreAndSendIdentifierInvite'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiIdaasSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiIdaasSdk\Model\GetInviteResponse|\Mydex\ApiIdaasSdk\Model\ErrorResponse|\Mydex\ApiIdaasSdk\Model\AuthErrorResponse
     */
    public function postStoreAndSendIdentifierInvite($invite_request_body = null, string $contentType = self::contentTypes['postStoreAndSendIdentifierInvite'][0])
    {
        list($response) = $this->postStoreAndSendIdentifierInviteWithHttpInfo($invite_request_body, $contentType);
        return $response;
    }

    /**
     * Operation postStoreAndSendIdentifierInviteWithHttpInfo
     *
     * Store an invitation code and send notification.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\InviteRequestBody|null $invite_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postStoreAndSendIdentifierInvite'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiIdaasSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiIdaasSdk\Model\GetInviteResponse|\Mydex\ApiIdaasSdk\Model\ErrorResponse|\Mydex\ApiIdaasSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function postStoreAndSendIdentifierInviteWithHttpInfo($invite_request_body = null, string $contentType = self::contentTypes['postStoreAndSendIdentifierInvite'][0])
    {
        $request = $this->postStoreAndSendIdentifierInviteRequest($invite_request_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\GetInviteResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiIdaasSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiIdaasSdk\Model\GetInviteResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\GetInviteResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiIdaasSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation postStoreAndSendIdentifierInviteAsync
     *
     * Store an invitation code and send notification.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\InviteRequestBody|null $invite_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postStoreAndSendIdentifierInvite'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postStoreAndSendIdentifierInviteAsync($invite_request_body = null, string $contentType = self::contentTypes['postStoreAndSendIdentifierInvite'][0])
    {
        return $this->postStoreAndSendIdentifierInviteAsyncWithHttpInfo($invite_request_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postStoreAndSendIdentifierInviteAsyncWithHttpInfo
     *
     * Store an invitation code and send notification.
     *
     * @param  \Mydex\ApiIdaasSdk\Model\InviteRequestBody|null $invite_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postStoreAndSendIdentifierInvite'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postStoreAndSendIdentifierInviteAsyncWithHttpInfo($invite_request_body = null, string $contentType = self::contentTypes['postStoreAndSendIdentifierInvite'][0])
    {
        $returnType = '\Mydex\ApiIdaasSdk\Model\GetInviteResponse';
        $request = $this->postStoreAndSendIdentifierInviteRequest($invite_request_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postStoreAndSendIdentifierInvite'
     *
     * @param  \Mydex\ApiIdaasSdk\Model\InviteRequestBody|null $invite_request_body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postStoreAndSendIdentifierInvite'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postStoreAndSendIdentifierInviteRequest($invite_request_body = null, string $contentType = self::contentTypes['postStoreAndSendIdentifierInvite'][0])
    {



        $resourcePath = '/members/invite';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($invite_request_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($invite_request_body));
            } else {
                $httpBody = $invite_request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
