<?php
/**
 * FtcSetupRequestBody
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiIdaasSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * IDaaS API
 *
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Mydex\ApiIdaasSdk\Model;

use \ArrayAccess;
use \Mydex\ApiIdaasSdk\ObjectSerializer;

/**
 * FtcSetupRequestBody Class Doc Comment
 *
 * @category Class
 * @description Request body for First Time Connection setup
 * @package  Mydex\ApiIdaasSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FtcSetupRequestBody implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'FtcSetupRequestBody';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'connection_nid' => 'string',
        'connection_token_hash' => 'string',
        'return_to' => 'string',
        'mydexid' => 'string',
        'version' => 'int',
        'linking_token' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'connection_nid' => null,
        'connection_token_hash' => null,
        'return_to' => null,
        'mydexid' => null,
        'version' => null,
        'linking_token' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'connection_nid' => false,
        'connection_token_hash' => false,
        'return_to' => false,
        'mydexid' => true,
        'version' => false,
        'linking_token' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'connection_nid' => 'connection_nid',
        'connection_token_hash' => 'connection_token_hash',
        'return_to' => 'return_to',
        'mydexid' => 'mydexid',
        'version' => 'version',
        'linking_token' => 'linking_token'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'connection_nid' => 'setConnectionNid',
        'connection_token_hash' => 'setConnectionTokenHash',
        'return_to' => 'setReturnTo',
        'mydexid' => 'setMydexid',
        'version' => 'setVersion',
        'linking_token' => 'setLinkingToken'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'connection_nid' => 'getConnectionNid',
        'connection_token_hash' => 'getConnectionTokenHash',
        'return_to' => 'getReturnTo',
        'mydexid' => 'getMydexid',
        'version' => 'getVersion',
        'linking_token' => 'getLinkingToken'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('connection_nid', $data ?? [], null);
        $this->setIfExists('connection_token_hash', $data ?? [], null);
        $this->setIfExists('return_to', $data ?? [], null);
        $this->setIfExists('mydexid', $data ?? [], null);
        $this->setIfExists('version', $data ?? [], null);
        $this->setIfExists('linking_token', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['connection_nid'] === null) {
            $invalidProperties[] = "'connection_nid' can't be null";
        }
        if ($this->container['connection_token_hash'] === null) {
            $invalidProperties[] = "'connection_token_hash' can't be null";
        }
        if ($this->container['return_to'] === null) {
            $invalidProperties[] = "'return_to' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets connection_nid
     *
     * @return string
     */
    public function getConnectionNid()
    {
        return $this->container['connection_nid'];
    }

    /**
     * Sets connection_nid
     *
     * @param string $connection_nid The connection NID
     *
     * @return self
     */
    public function setConnectionNid($connection_nid)
    {
        if (is_null($connection_nid)) {
            throw new \InvalidArgumentException('non-nullable connection_nid cannot be null');
        }
        $this->container['connection_nid'] = $connection_nid;

        return $this;
    }

    /**
     * Gets connection_token_hash
     *
     * @return string
     */
    public function getConnectionTokenHash()
    {
        return $this->container['connection_token_hash'];
    }

    /**
     * Sets connection_token_hash
     *
     * @param string $connection_token_hash The hashed connection token
     *
     * @return self
     */
    public function setConnectionTokenHash($connection_token_hash)
    {
        if (is_null($connection_token_hash)) {
            throw new \InvalidArgumentException('non-nullable connection_token_hash cannot be null');
        }
        $this->container['connection_token_hash'] = $connection_token_hash;

        return $this;
    }

    /**
     * Gets return_to
     *
     * @return string
     */
    public function getReturnTo()
    {
        return $this->container['return_to'];
    }

    /**
     * Sets return_to
     *
     * @param string $return_to The URL to return to after connection
     *
     * @return self
     */
    public function setReturnTo($return_to)
    {
        if (is_null($return_to)) {
            throw new \InvalidArgumentException('non-nullable return_to cannot be null');
        }
        $this->container['return_to'] = $return_to;

        return $this;
    }

    /**
     * Gets mydexid
     *
     * @return string|null
     */
    public function getMydexid()
    {
        return $this->container['mydexid'];
    }

    /**
     * Sets mydexid
     *
     * @param string|null $mydexid The MydexID if already known (required if version > 1)
     *
     * @return self
     */
    public function setMydexid($mydexid)
    {
        if (is_null($mydexid)) {
            array_push($this->openAPINullablesSetToNull, 'mydexid');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('mydexid', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['mydexid'] = $mydexid;

        return $this;
    }

    /**
     * Gets version
     *
     * @return int|null
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param int|null $version The connection version (default 1, must be >= 1)
     *
     * @return self
     */
    public function setVersion($version)
    {
        if (is_null($version)) {
            throw new \InvalidArgumentException('non-nullable version cannot be null');
        }
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets linking_token
     *
     * @return string|null
     */
    public function getLinkingToken()
    {
        return $this->container['linking_token'];
    }

    /**
     * Sets linking_token
     *
     * @param string|null $linking_token A unique ID representing the member in the subscriber's backend
     *
     * @return self
     */
    public function setLinkingToken($linking_token)
    {
        if (is_null($linking_token)) {
            array_push($this->openAPINullablesSetToNull, 'linking_token');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('linking_token', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['linking_token'] = $linking_token;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


