<?php
/**
 * FtcSetupRequestBodyTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiIdaasSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * IDaaS API
 *
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mydex\ApiIdaasSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FtcSetupRequestBodyTest Class Doc Comment
 *
 * @category    Class
 * @description Request body for First Time Connection setup
 * @package     Mydex\ApiIdaasSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FtcSetupRequestBodyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FtcSetupRequestBody"
     */
    public function testFtcSetupRequestBody()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "connection_nid"
     */
    public function testPropertyConnectionNid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "connection_token_hash"
     */
    public function testPropertyConnectionTokenHash()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "return_to"
     */
    public function testPropertyReturnTo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mydexid"
     */
    public function testPropertyMydexid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "linking_token"
     */
    public function testPropertyLinkingToken()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
