<?php
/**
 * IdentifiersApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiIdaasSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * IDaaS API
 *
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Mydex\ApiIdaasSdk\Test\Api;

use \Mydex\ApiIdaasSdk\Configuration;
use \Mydex\ApiIdaasSdk\ApiException;
use \Mydex\ApiIdaasSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * IdentifiersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Mydex\ApiIdaasSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IdentifiersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getIdentifierInvite
     *
     * Fetch an invitation code and identifier auth data..
     *
     */
    public function testGetIdentifierInvite()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchNotifyStatus
     *
     * Update the status of a notification..
     *
     */
    public function testPatchNotifyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postInviteStatus
     *
     * Check the status of an invite..
     *
     */
    public function testPostInviteStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postNotifyMemberViaIdentifier
     *
     * Send a notification to a member via its identifier..
     *
     */
    public function testPostNotifyMemberViaIdentifier()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postStoreAndSendIdentifierInvite
     *
     * Store an invitation code and send notification..
     *
     */
    public function testPostStoreAndSendIdentifierInvite()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
